module "dockeree-cluster" {
  source                      = "github.com/IGNW/terraform-vsphere-docker-ee"

  environment                 = "centos"
  vsphere_server              = "10.254.252.5"
  vsphere_datacenter          = "POC-Lab"

  manager_vsphere_datastore   = "10.254.252.23_Datastore"
  manager_vsphere_cluster     = "POC"
  manager_vsphere_network     = "ignw-poc|vesta-devops|servers"
  manager_vm_template	      = "centos7_template_dockeree2"

  worker_a_label	      = "mwt"
  worker_a_vsphere_datastore  = "10.254.252.23_Datastore"
  worker_a_vsphere_cluster    = "POC"
  worker_a_vsphere_network    = "ignw-poc|vesta-devops|servers"
  worker_a_vm_template	      = "centos7_template_dockeree2"

  worker_b_label              = "wrk1"
  worker_b_vsphere_datastore  = "10.254.252.23_Datastore"
  worker_b_vsphere_cluster    = "POC"
  worker_b_vsphere_network    = "ignw-poc|vesta-devops|servers"
  worker_b_vm_template	      = "centos7_template_dockeree2"

  vsphere_folder              = "dockeree-centos"
  domain                      = "ignw.io"
  manager_node_count          = "3"
  worker_a_node_count         = "1"
  worker_b_node_count         = "1"
  dtr_node_count              = "3"
  dtr_nfs_url                 = ""
  vsphere_user                = "administrator@vsphere.local"
  vsphere_password            = "Ignw!098"
  ssh_username                = "root"
  ssh_password                = "changeme1"
  ucp_admin_password          = "ucpw123!"
  dtr_root_volume_size        = "40"
  worker_root_volume_size     = "40"
  manager_root_volume_size    = "40"
  scsi_type                   = "pvscsi"
  script_path                 = "/tmp"
  dockeree_license	      = ""
}
