module "dockeree-cluster" {
  source                  = "github.com/IGNW/terraform-vsphere-dockeree?ref=1.0.0"

  environment             = "labtest"
  vsphere_server          = "10.254.252.5"
  vsphere_datacenter      = "POC-Lab"
  vsphere_datastore       = "10.254.252.23_Datastore"
  vsphere_compute_cluster = "POC"
  vsphere_network         = "ignw-poc|vesta-devops|servers"
  vsphere_folder          = "dockeree-lab"
  vm_template             = "centos7_template_dockeree"
  domain                  = "ignw.io"
  manager_node_count      = "2"
  worker_node_count       = "1"
  dtr_node_count          = "1"
  vsphere_user            = "administrator@vsphere.local"
  vsphere_password        = "${var.vsphere_password}"
  ssh_username            = "adminuser"
  ssh_password            = "${var.ssh_password}"
  ucp_admin_password      = "${var.ucp_admin_password}"
}
